### ISSUE TITLE
pheasant use string_types which is not provided by mkdocs 

### ISSUE THREAD

**Issue by zhcf** [daizutabi/pheasant#10]
mkdocs build
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/__main__.py", line 159, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/config_options.py", line 130, in validate
    return self.run_validation(value)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/config_options.py", line 591, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/config_options.py", line 599, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/pheasant/plugins/mkdocs.py", line 8, in <module>
    from mkdocs.utils import markdown_extensions, string_types
ImportError: cannot import name 'string_types'

**Comment by daizutabi** [comment]
Please update your pheasant package to the latest version.

See [this PR](https://github.com/daizutabi/pheasant/pull/6) for this issue.

**Comment by zhcf** [comment]
The latest package on pip is pheasant-2.1.6, I am using this package.  so you mean I should copy the latest git code to site-packages.

Thanks

**Comment by daizutabi** [comment]
I can see the version is now 2.5.2 on [pypi](https://pypi.org/project/pheasant/).
The below is the log message when I run `pip install pheasant`:

Installing collected packages: colorama, zipp, importlib-metadata, markdown, click, MarkupSafe, jinja2, termcolor, decorator, six, ipython-genutils, traitlets, tornado, python-dateutil, pywin32, jupyter-core, pyzmq, jupyter-client, backcall, parso, jedi, pygments, wcwidth, prompt-toolkit, pickleshare, ipython, ipykernel, pheasant
Successfully installed MarkupSafe-1.1.1 backcall-0.1.0 click-7.1.2 colorama-0.4.3 decorator-4.4.2 importlib-metadata-1.6.0 ipykernel-5.2.1 ipython-7.14.0 ipython-genutils-0.2.0 jedi-0.17.0 jinja2-2.11.2 jupyter-client-6.1.3 jupyter-core-4.6.3 markdown-3.2.2 parso-0.7.0 **pheasant-2.5.2** pickleshare-0.7.5 prompt-toolkit-3.0.5 pygments-2.6.1 python-dateutil-2.8.1 pywin32-227 pyzmq-19.0.1 six-1.14.0 termcolor-1.1.0 tornado-6.0.4 traitlets-4.3.3 wcwidth-0.1.9 zipp-3.1.0


I don't know why you can't install the latest version via pip.

**Comment by tsalo** [comment]
I think it's a Python version issue. I also came across this problem today but realized that `pheasant` requires 3.7, while both the original poster and I are using 3.6. Switching to a 3.7 environment fixed it for me.
