### ISSUE TITLE
Comment in python inline code leads to problem

### ISSUE THREAD

**Issue by michaelwimmer** [daizutabi/pheasant#5]
I noticed that for inline code having a python comment inside the fenced code block raises an Exception. For example

````
```python inline
a = 1
#Test comment
print(a)
```
````

gives the following error:

```
[E 191125 18:22:59 ioloop:909] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/livereload/handlers.py", line 69, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/livereload/watcher.py", line 105, in examine
        func()
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 114, in builder
        build(config, live_server=live_server, dirty=dirty)
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/mkdocs/commands/build.py", line 270, in build
        nav = config['plugins'].run_event('nav', nav, config=config, files=files)
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/mkdocs/plugins.py", line 94, in run_event
        result = method(item, **kwargs)
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/plugins/mkdocs.py", line 89, in on_nav
        self.converter.convert_from_files(paths)
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/core/converter.py", line 188, in convert_from_files
        return self._convert_from_files(paths)
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/core/pheasant.py", line 63, in _convert_from_files
        self.convert(path)
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/core/converter.py", line 179, in convert
        output = self._convert(path)
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/core/pheasant.py", line 51, in _convert
        return self.convert_by_name(path, "main")
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/core/converter.py", line 137, in convert_by_name
        source = self.parse(source, name)
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/core/converter.py", line 108, in parse
        return self.parsers[name].parse(source)
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/core/parser.py", line 62, in parse
        return "".join(iterator())
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/core/parser.py", line 53, in iterator
        cell.output = cell.parse(splitter, self)
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/core/base.py", line 114, in parse
        return "".join(self.render(splitter, parser))
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/core/base.py", line 111, in _render
        yield from render(self.context, splitter, parser)
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/core/decorator.py", line 56, in render_
        yield from render(self, context, splitter, parser)
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/renderers/jupyter/jupyter.py", line 100, in render_inline_code
        code, context["option"] = split_option(context["code"])
      File "/home/michael/anaconda3/envs/lectures/lib/python3.8/site-packages/pheasant/renderers/jupyter/jupyter.py", line 230, in split_option
        code, option = code.split("#")
    ValueError: too many values to unpack (expected 2)

```

**Comment by mdrobisch** [comment]
Getting the same error.
In addition an import of python-files with  `{ % file.py % }` is only possible for files without comments.
The comments otherwise will be interpreted as markdown.
Is constribution to fix this wanted here (just an offer)?
